# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4675408e8543da4f042dfbb900f186f4f360d4f34acc56c6cf6581a7ac78d829e41e16b34587411693be67962540a1771d1fec50bf53877d71af41fcfcc573e

test:
  secret_key_base: 37cd661ae33c95af27ab2c00c8ae12f541473eaa3fd86d02255f857e3d834ffda2f91150eb730aadbe00612e5b745ea7089121d8bbfce57df7f126a1c63c21c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
